service: sparshablog
image: sparshalc/blog
servers:
  web:
    - 167.172.160.52
registry:
  username: sparshalc
  password:
    - KAMAL_REGISTRY_PASSWORD
proxy:
  host: sparshalamichhane.com.np
  ssl: true
  app_port: 3000
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  arch: amd64
volumes:
  - "sparsha_volume:/rails/storage"
